# Generated by Django 4.1.7 on 2023-05-24 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='selling_rice',
            new_name='selling_price',
        ),
    ]
